
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_3_H_ConsoleApp2;

// Create single instance of sample data from first line of dataset for model input
MLModel_3_H.ModelInput sampleData = new MLModel_3_H.ModelInput()
{
    Date = @"13/08/16",
    HomeTeam = @"Crystal Palace",
    AwayTeam = @"West Brom",
    HS = 14F,
    AS = 13F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel_3_H.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual FTHG with predicted FTHG from sample data...\n\n");


Console.WriteLine($"Date: {@"13/08/16"}");
Console.WriteLine($"HomeTeam: {@"Crystal Palace"}");
Console.WriteLine($"AwayTeam: {@"West Brom"}");
Console.WriteLine($"FTHG: {0F}");
Console.WriteLine($"HS: {14F}");
Console.WriteLine($"AS: {13F}");


Console.WriteLine($"\n\nPredicted FTHG: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

