
// This file was auto-generated by ML.NET Model Builder. 

using MLModel2_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel2.ModelInput sampleData = new MLModel2.ModelInput()
{
    Date = @"13/08/16",
    HomeTeam = @"Crystal Palace",
    AwayTeam = @"West Brom",
    Referee = @"C Pawson",
    HS = 14F,
    AS = 13F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel2.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual FTR with predicted FTR from sample data...\n\n");


Console.WriteLine($"Date: {@"13/08/16"}");
Console.WriteLine($"HomeTeam: {@"Crystal Palace"}");
Console.WriteLine($"AwayTeam: {@"West Brom"}");
Console.WriteLine($"FTR: {@"A"}");
Console.WriteLine($"Referee: {@"C Pawson"}");
Console.WriteLine($"HS: {14F}");
Console.WriteLine($"AS: {13F}");


Console.WriteLine($"\n\nPredicted FTR: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

